"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _discover from './discover.bones.json'
import _extension_auth from './extension-auth.bones.json'
import _extension_callback from './extension-callback.bones.json'

registerBones({
  "discover": _discover,
  "extension-auth": _extension_auth,
  "extension-callback": _extension_callback,
})
